name: Axiom
version: '1.0'
main: net.kroesch.axiom.AxiomPlugin
api-version: '1.21'
commands:
  hallo:
    description: Ein einfacher Testbefehl
    usage: /<command>
  cleararea:
    description: Löscht alle Blöcke in einem Rechteck um dich herum.
    usage: /<command> <länge> <breite>
    aliases: [ ca, clearrect ]
  buildwall:
    description: Baut eine Mauer mit fester Stärke um dich herum.
    usage: /<command> <länge> <breite> <höhe> [material]
    aliases: [ bw, wall ]
  digtunnel:
    description: Gräbt einen 2x2 Tunnel mit Schienen und Fackeln.
    usage: /<command> <länge>
    aliases: [dt, tunnel]
  spiralstair:
    description: Baut eine spiralförmige Treppe nach unten um einen 2x2 Kern.
    usage: /spiralstair <depth>
    aliases: [ss, spiral]
  buildportal:
    description: Baut ein Nether-Portal am Standort des Spielers.
    usage: /<command>
    permission: axiom.command.buildportal
